package com.cch.model;

import java.sql.Timestamp;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.id
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.user_id
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.user_name
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.user_password
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.status
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.reg_date
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    private Timestamp regDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.user_role
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    private String userRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.id
     *
     * @return the value of public.user.id
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.id
     *
     * @param id the value for public.user.id
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.user_id
     *
     * @return the value of public.user.user_id
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.user_id
     *
     * @param userId the value for public.user.user_id
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.user_name
     *
     * @return the value of public.user.user_name
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.user_name
     *
     * @param userName the value for public.user.user_name
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.user_password
     *
     * @return the value of public.user.user_password
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.user_password
     *
     * @param userPassword the value for public.user.user_password
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.status
     *
     * @return the value of public.user.status
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.status
     *
     * @param status the value for public.user.status
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.reg_date
     *
     * @return the value of public.user.reg_date
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public Timestamp getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.reg_date
     *
     * @param regDate the value for public.user.reg_date
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public void setRegDate(Timestamp regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.user_role
     *
     * @return the value of public.user.user_role
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.user_role
     *
     * @param userRole the value for public.user.user_role
     *
     * @mbg.generated Sun May 31 09:29:36 CST 2020
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }
}