version: "3.8"
services:
  postgres:
    restart: always
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: postgres_docker_container
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cch
      POSTGRES_PASSWORD: cch
      POSTGRES_DB: cch
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    restart: always
    build:
      context: .
      dockerfile: redis.dockerfile
    container_name: redis_docker_container
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_docker_container
    privileged: true
    ports: 
      - 4100:80
    environment: 
      NGINX_PORT: 80
    volumes: 
      - ./data/nginx/html:/usr/share/nginx/html
      - ./config/nginx:/etc/nginx/templates
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
