package com.cch.mapper;

import com.cch.model.Comment;
import java.util.List;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comment
     *
     * @mbg.generated Sun May 31 10:20:44 CST 2020
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comment
     *
     * @mbg.generated Sun May 31 10:20:44 CST 2020
     */
    List<Comment> selectAll();
}