package com.cch.mapper;

import com.cch.model.Content;
import java.util.List;

public interface ContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.content
     *
     * @mbg.generated Sun May 31 10:20:44 CST 2020
     */
    int insert(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.content
     *
     * @mbg.generated Sun May 31 10:20:44 CST 2020
     */
    List<Content> selectAll();
}