name: ESLint

on:
    push:
        branches:
            - master
    
    pull_request:
        branches:
            - master

defaults:
    run:
        shell: bash
        working-directory: cch-web

jobs:
    ESLint:
        name: ESLint Code Review
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Set Node.js environment
              uses: actions/setup-node@v2.1.0

            - name: Init Node.js Context
              run: |
                cp package-lint.json package.json
                cd cch-web && npm install

